name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest
    - name: Push image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest
